### PR TITLE
Mcnp

### PR DESCRIPTION
**Pull request by markNbaHoang12**
Created and adjusted python files to properly process both njoy and chitech outputs (.csx) files.
Summary:
- minor adjustment to generate_njoy_mgxs.py to print error if both ENDF files are not given
- For files in njoy_isotope_processor: Initiate and process njoy outputs then produce chitech files for isotopes
- For files in chitech_composite_processor:
+ Process Chitech outputs
+ Solve the infinite medium equation with source condition
+ If given, plot the spectra
+ If given, compare njoy results with mcnp and other njoy results

### CODE REVIEW

**Review by markNbaHoang12 — COMMENTED** [review]
I accidentally delete this file (Utils_ChiTechCombiner) when I was removing the other unnecessary ones. Please keep this file and do not remove it as it is important for the chi-tech processor

**Review by ragusa — CHANGES_REQUESTED** [review]
In this PR, there are file in a folder called: njoy_isotope_processor.

If I accept this PR, then I will have a folder called njoy_isotope_processor and another one called njoy_processor.

Because the orignal code from Jan only has a folder called njoy_processor, and because I forked my repo from his, we need to keep some contiunity between folders. 

Therefore, exaplin why there are files in njoy_isotope_processor and determine whether they are needed or not, when compared tot he one in njoy_processor

**Comment by markNbaHoang12** [comment]
Please don't merge this pull request. This one we scrapped a month ago
because I accidentally created the new folder njoy_isotope_processor. The
files in there are outdated and unnecessary. I redid the commit with a new
directory that has the changes done directly onto the existing folder
njoy_processor so there shouldn't be any conflicts.

The new commit name is "Redo the commit ....." that I sent in most
recently. Please take a look at that one. It should have the most recent
and necessary changes. I'm sorry I couldn't be of more help. I'm currently
outside right now and doesn't have access to a computer at the moment. I'll
answer any of your further questions in more detail once i'm back home.

Thank you Dr. Ragusa !

Mark Nguyen

**Comment by ragusa** [comment]
No worries. I was just trying to catch up. I remember now, there is that other PR. ‘ll take a look.

Do you have time Monday morning for a zoom meeting? I have time until 9:45am. Let me know!

**Comment by markNbaHoang12** [comment]
I'm sorry but I don't think I do. I have classes consecutively from 8am to
11:15 am in the AIEN building. I have a free period from 11:30-1:30 in
between classes so I don't think i'll be able to meet with you before 9:45.
I have the entirety of Tuesday free so is it okay if we meet then ?

**Pull request closed without merging**
